In [67]:
#Name: Vineet Dcunha
#"I have not given or received any unauthorized assistance on this assignment."

import numpy as np
a = np.arange(0,100)
# create a numpy a array with the start number as 0 and end number as 100 and equally spaced numbers
print ('Returns equally spaced values in the range 0 through 100')
print (a)

Returns equally spaced values in the range 0 through 100
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [68]:
b = np.arange(0,100,10)
# create a numpy b array with the start number as 0 and end number as 100 and 10 equally spaced numbers
print ('Returns 10 equally spaced values in the range 0 through 100')
print (b)

Returns 10 equally spaced values in the range 0 through 100
[ 0 10 20 30 40 50 60 70 80 90]


In [69]:
c = np.linspace(0,10,num = 100)
# create a numpy c array with the start number as 0 and end number as 100 and generates 100 numbers equally spaced
print ('Returns values spaced at 0.1 in the range 0 through 10')
print (c)

Returns values spaced at 0.1 in the range 0 through 10
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777

In [70]:
d = np.random.random((10,10))
# create a numpy d array with random numbers and 10*10 matrix
print ('Returning an array of 10*10 random numbers')
print (d)

Returning an array of 10*10 random numbers
[[0.39973725 0.87762384 0.76008349 0.50330654 0.2493384  0.51596297
  0.78878545 0.21969195 0.68983254 0.26340114]
 [0.60714896 0.93497179 0.811149   0.80134063 0.99445172 0.67003754
  0.369788   0.8463387  0.83144532 0.24642462]
 [0.51670416 0.61897192 0.61300671 0.83018585 0.44994892 0.89451139
  0.94934994 0.10693089 0.7165912  0.93214484]
 [0.61544569 0.61431262 0.8669082  0.51431874 0.07030219 0.22633447
  0.97772483 0.95774908 0.53706094 0.68252389]
 [0.78081042 0.76042725 0.93002358 0.02010845 0.18415271 0.44721854
  0.22796889 0.59610844 0.02080737 0.16839995]
 [0.25040053 0.59623055 0.96652612 0.47988279 0.56721299 0.52786392
  0.68456265 0.21531013 0.63201047 0.99685837]
 [0.69366659 0.22950947 0.12632029 0.09120505 0.34212657 0.98741516
  0.93346858 0.63972874 0.00920969 0.34793851]
 [0.91942115 0.33302363 0.81123693 0.01461206 0.69756091 0.02014383
  0.17844    0.97558621 0.04974356 0.73362656]
 [0.85055087 0.33865346 0.0025001  0.

In [71]:
a = a.reshape(10,10)
# Modifies the shape of a in 10*10 matrix
print ('Reshaping the array a of 100 numbers in 10*10 format')
print (a)

Reshaping the array a of 100 numbers in 10*10 format
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [72]:
result1 = a[4,5]
# Returns element at specific position
print ('The result returns the element in an array at position [4,5]:', result1)
print (result1)

The result returns the element in an array at position [4,5]: 45
45


In [73]:
result2 = a[4]
# Returns element at specific position
print ('The result returns all the numbers at row [4]:', result2)
print (result2)

The result returns all the numbers at row [4]: [40 41 42 43 44 45 46 47 48 49]
[40 41 42 43 44 45 46 47 48 49]


In [74]:
result3 = sum(d)
# Adds numbers in array d row wise
print ('Adds all the numbers in array d on each row')
print (result3)
# Adds all numbers in array d
print ('\nAdds all the numbers in array d')
print (sum(result3))

Adds all the numbers in array d on each row
[6.46120481 6.18002831 6.85718202 5.1589892  4.65554498 5.19925295
 5.64119001 5.45149129 4.44586039 4.97042912]

Adds all the numbers in array d
55.02117309382868


In [75]:
result4 = a.max()
# Returns max number in array a
print ('Returns the maximum number from array a')
print (result4)

Returns the maximum number from array a
99


In [76]:
result5 = b.transpose()
# Returns the transpose of array b
print ('Returns the transpose of array b')
print (result5)

Returns the transpose of array b
[ 0 10 20 30 40 50 60 70 80 90]


In [77]:
result6 = a + d
# Adds all the numbers in array a and d at each position
print ('Adds all the numbers in array a and array d for each position')
print (result6)

Adds all the numbers in array a and array d for each position
[[ 0.39973725  1.87762384  2.76008349  3.50330654  4.2493384   5.51596297
   6.78878545  7.21969195  8.68983254  9.26340114]
 [10.60714896 11.93497179 12.811149   13.80134063 14.99445172 15.67003754
  16.369788   17.8463387  18.83144532 19.24642462]
 [20.51670416 21.61897192 22.61300671 23.83018585 24.44994892 25.89451139
  26.94934994 27.10693089 28.7165912  29.93214484]
 [30.61544569 31.61431262 32.8669082  33.51431874 34.07030219 35.22633447
  36.97772483 37.95774908 38.53706094 39.68252389]
 [40.78081042 41.76042725 42.93002358 43.02010845 44.18415271 45.44721854
  46.22796889 47.59610844 48.02080737 49.16839995]
 [50.25040053 51.59623055 52.96652612 53.47988279 54.56721299 55.52786392
  56.68456265 57.21531013 58.63201047 59.99685837]
 [60.69366659 61.22950947 62.12632029 63.09120505 64.34212657 65.98741516
  66.93346858 67.63972874 68.00920969 69.34793851]
 [70.91942115 71.33302363 72.81123693 73.01461206 74.69756091 7

In [78]:
result7 = a * d
# Multiplies all the numbers in array a and d at each position
print ('Multiplies all the numbers in array a and array d for each position')
print (result7)

Multiplies all the numbers in array a and array d for each position
[[ 0.          0.87762384  1.52016698  1.50991963  0.99735362  2.57981486
   4.73271272  1.53784364  5.51866031  2.37061023]
 [ 6.07148963 10.28468965  9.73378803 10.4174282  13.92232413 10.05056303
   5.91660808 14.38775797 14.96601584  4.68206769]
 [10.3340832  12.9984103  13.4861476  19.09427447 10.7987742  22.36278476
  24.68309832  2.88713391 20.06455361 27.03220044]
 [18.4633708  19.04369131 27.74106227 16.97251829  2.39027461  7.92170633
  35.19809376 35.43671579 20.40831576 26.61843169]
 [31.23241686 31.17751722 39.06099049  0.86466346  8.10271905 20.12483444
  10.48656912 28.01709691  0.99875378  8.25159762]
 [12.52002668 30.40775805 50.25935837 25.43378762 30.62950156 29.03251573
  38.3355086  12.27267725 36.65660706 58.81464401]
 [41.61999566 14.00007758  7.83185826  5.7459183  21.8961005  64.18198514
  61.60892618 42.86182542  0.62625863 24.00775697]
 [64.3594807  23.64467754 58.40905875  1.0666801  51.6195

In [79]:
result8 = np.dot(a , d)
# Returns the dot product all the numbers in array a and d at each position
print ('Dot Product all the numbers in array a and array d for each position')
print (result8)

Dot Product all the numbers in array a and array d for each position
[[ 32.7103658   24.34289921  28.37204139  23.34248466  22.21962254
   20.97584268  21.0468706   26.0646538   16.11688921  22.19998496]
 [ 97.32241389  86.14318231  96.94386161  74.93237666  68.77507238
   72.96837219  77.45877071  80.57956674  60.57549311  71.90427618]
 [161.93446198 147.94346542 165.51568184 126.52226865 115.33052223
  124.9609017  133.87067082 135.09447968 105.03409701 121.6085674 ]
 [226.54651007 209.74374852 234.08750206 178.11216065 161.88597207
  176.95343121 190.28257094 189.60939261 149.49270091 171.31285862]
 [291.15855816 271.54403163 302.65932229 229.70205265 208.44142191
  228.94596072 246.69447105 244.12430555 193.95130481 221.01714984]
 [355.77060625 333.34431473 371.23114251 281.29194465 254.99687175
  280.93849022 303.10637116 298.63921849 238.40990872 270.72144106]
 [420.38265434 395.14459784 439.80296274 332.88183664 301.5523216
  332.93101973 359.51827128 353.15413142 282.86851262 3